const TITAN_FORWARDING_THEME_VARIANT_KEY = 'TITAN_FORWARDING_THEME_VARIANT_KEY';
const BASE_SERVER_URL = 'http://localhost:5000/api/v1';
const TITAN_FORWARDING_LANGUAGE = 'en-US';


export const TITAN_FORWARDING_CONSTANTS = {
    TITAN_FORWARDING_THEME_VARIANT_KEY,
    BASE_SERVER_URL,
    TITAN_FORWARDING_LANGUAGE
};